deployment:
  name: example
  image:
    name: nginx
    tag: latest
    pullPolicy: Always
  restartPolicy: Always
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"